# Generated by Django 6.0.7 on 2026-07-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
