# Generated by Django 6.0.7 on 2026-07-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
